abstract class AppConstants {
  static const List<(String name, String imagePath, String title)> latestNews = [
    ('“West Ham” Wins Conference League!',
    'assets/images/classic_soccer_01.jpg',
    'West Ham United triumphed in the UEFA Conference League, clinching their first major European trophy in decades. The match was a thrilling encounter, with goals from key players sealing the victory. Fans erupted in celebration as their team showcased dominance on the field. This historic win solidifies West Ham’s position as a rising force in European football and brings hope for more success in future campaigns.',
    ),
    ('Liverpool vs Manchester United',
    'assets/images/classic_soccer_02.jpg',
    'The rivalry between Liverpool and Manchester United reached new heights in their latest clash. With both teams fighting for Premier League glory, the game was filled with drama, goals, and intense moments. Liverpool’s dynamic attack proved too much for United’s defense, securing a vital victory. This match further ignites the fierce competition between these historic clubs, thrilling fans worldwide.',
    ),
    ('Arsenal’s Title Hopes Still Alive',
    'assets/images/classic_soccer_03.jpg',
    'Arsenal continues to impress this season with their eye-catching performances. Despite setbacks, they remain in contention for the Premier League title. Young talents like Bukayo Saka and Gabriel Martinelli are leading the charge, supported by an experienced midfield. As the race tightens, Arsenal’s resilience will be tested in upcoming fixtures that could define their season.',
    ),
    ('Real Madrid Signs New Star Forward',
    'assets/images/classic_soccer_04.jpg',
    'Real Madrid announced the signing of a promising young forward who has already made waves in international football. The transfer deal highlights Madrid’s commitment to strengthening their squad for future challenges. Fans eagerly anticipate how this new addition will blend with the likes of Vinícius Júnior and Karim Benzema in their pursuit of European glory.',
    ),
    ('Barcelona’s Resurgence Under Xavi',
    'assets/images/classic_soccer_05.jpg',
    'Under Xavi Hernandez’s leadership, FC Barcelona is experiencing a resurgence. The team’s tactical improvements and emphasis on youth development have brought consistent results. With Pedri and Gavi dazzling in midfield, Barcelona is climbing back to the top of La Liga. This revival marks a turning point for the Catalan giants after years of struggles.',
    ),
    ('Erling Haaland Breaks Goal Record',
    'assets/images/classic_soccer_06.jpg',
    'Manchester City’s Erling Haaland has shattered the Premier League’s single-season goal-scoring record. With his lethal finishing and athleticism, Haaland has become a nightmare for defenders. This achievement cements his place as one of the world’s best strikers, raising City’s chances of clinching both domestic and European titles.',
    ),
    ('Chelsea Struggles Despite Big Spending',
    'assets/images/classic_soccer_07.jpg',
    'Chelsea FC’s season has been marred by inconsistency, despite their record-breaking transfers. With a star-studded squad, fans expected better results. However, managerial changes and tactical issues have hindered progress. The Blues now face a tough battle to secure European football next season, raising questions about their long-term strategy.',
    ),
    ('Napoli’s Historic Serie A Triumph',
    'assets/images/classic_soccer_08.jpg',
    'SSC Napoli clinched their first Serie A title in over three decades, led by a stellar performance from Victor Osimhen and Khvicha Kvaratskhelia. Their attacking flair and solid defense outclassed competitors, earning widespread praise. Napoli’s victory sparked celebrations across Naples, symbolizing a golden era for the club in Italian football.',
    ),
  ];

  static const List<(String name, String imagePath, String title)> americanSoccer = [
    ('Major League Soccer\'s Rising Stars',
      'assets/images/american_soccer_01.jpg',
      'The MLS continues to grow in prominence, showcasing young talent from across the globe. Players like Thiago Almada and Cade Cowell have gained international recognition for their performances. With academies investing in youth development, the future of American soccer looks brighter than ever. The league\'s commitment to nurturing talent is creating a pathway for players to shine domestically and internationally.',
    ),
    ('The Impact of David Beckham\'s Inter Miami',
    'assets/images/american_soccer_02.jpg',
    'Since its debut in 2020, Inter Miami has shaken up American soccer. Led by David Beckham, the team has attracted big names, including Lionel Messi, creating buzz both on and off the field. Their success highlights the MLS\'s growing appeal to global superstars. Inter Miami\'s vision emphasizes soccer\'s cultural impact in the United States, bringing international attention to the league.',
    ),
    ('USA Men\'s National Team\'s New Era',
    'assets/images/american_soccer_03.jpg',
    'The U.S. Men’s National Team is entering a new golden era. With stars like Christian Pulisic, Weston McKennie, and Gio Reyna leading the charge, they’re aiming to make a deep run in the 2026 World Cup, which the U.S. will co-host. The focus is now on blending youth and experience to compete against the world’s best teams.',
    ),
    ('Women\'s Soccer Shines in the USA',
    'assets/images/american_soccer_04.jpg',
    'The U.S. Women\'s National Team remains a powerhouse, dominating international tournaments and inspiring generations. Players like Megan Rapinoe and Alex Morgan have become household names. The National Women’s Soccer League (NWSL) is also growing, providing a platform for emerging talent to showcase their skills.',
    ),
    ('How Soccer is Growing in American Schools',
    'assets/images/american_soccer_05.jpg',
    'Youth soccer is thriving in the U.S., with schools and academies embracing the sport like never before. Programs are focused on providing high-quality coaching and competitive opportunities. This surge in grassroots support is helping create a pipeline for future MLS and national team stars.',
    ),
    ('Top MLS Rivalries You Should Know',
    'assets/images/american_soccer_06.jpg',
    'Rivalries are what make soccer thrilling, and MLS is no exception. Matches like LA Galaxy vs. LAFC and Portland Timbers vs. Seattle Sounders are among the most intense. These games are known for their electrifying atmospheres, passionate fans, and fierce competition, contributing to the league\'s growing reputation.',
    ),
    ('Hosting the 2026 World Cup: USA\'s Plans',
    'assets/images/american_soccer_07.jpg',
    'The U.S. is preparing to co-host the 2026 World Cup alongside Canada and Mexico. This monumental event is expected to boost soccer\'s popularity in America. Cities like Los Angeles, New York, and Miami will host matches, bringing fans from around the world to experience American soccer culture firsthand.',
    ),
    ('The Rise of Latino Influence in MLS',
    'assets/images/american_soccer_08.jpg',
    'Latino players and fans are shaping the future of soccer in America. From Carlos Vela\'s stellar performances for LAFC to the passionate fan bases in cities like Houston and Los Angeles, their impact is undeniable. MLS clubs are also tapping into Latin American markets for talent, enhancing the league\'s competitiveness and appeal.',
    ),
  ];

  static const List<(String name, String imagePath, String title)> classicSoccer = [
    ('The Magic of Pelé: A Soccer Icon',
    'assets/images/classic_soccer_09.jpg',
    'Pelé, known as "The King of Soccer," remains one of the greatest players of all time. With three World Cup titles and countless goals, his impact on the sport is unparalleled. This article explores his journey from humble beginnings in Brazil to becoming a global ambassador for the beautiful game.',
    ),
    ('Diego Maradona’s Hand of God Legacy',
    'assets/images/classic_soccer_10.jpg',
    'Diego Maradona’s name is forever etched in soccer history. His infamous "Hand of God" goal and his mesmerizing solo effort against England in the 1986 World Cup defined his genius. This article examines the triumphs and controversies of the Argentine legend’s career.',
    ),
    ('The Legendary Rivalry: Messi vs Ronaldo',
    'assets/images/classic_soccer_11.jpg',
    'Lionel Messi and Cristiano Ronaldo have defined modern soccer with their extraordinary skill and consistency. This piece explores their unique playing styles, record-breaking achievements, and how they’ve kept fans divided over who is the greatest of all time.',
    ),
    ('Zidane’s Mastery: A Midfield Maestro',
    'assets/images/classic_soccer_12.jpg',
    'Zinedine Zidane dazzled fans with his incredible vision, control, and skill. From his iconic volley in the 2002 Champions League final to his leadership on the French national team, Zidane’s legacy as one of soccer’s all-time greats is secure.',
    ),
    ('The Miracle of Istanbul: 2005 Final',
    'assets/images/classic_soccer_13.jpg',
    'The 2005 UEFA Champions League final between Liverpool and AC Milan is one of soccer’s greatest comebacks. Down 3-0 at halftime, Liverpool rallied to equalize and win in a dramatic penalty shootout. This article relives the emotions of that unforgettable night.',
    ),
    ('The Birth of Total Football',
    'assets/images/classic_soccer_14.jpg',
    'The Dutch team of the 1970s revolutionized soccer with their "Total Football" philosophy. Led by Johan Cruyff, they captivated the world with fluid movement and tactical brilliance. This piece explores how this approach changed the way soccer is played forever.',
    ),
    ('Brazil’s 1970 World Cup Dominance',
    'assets/images/classic_soccer_15.jpg',
    'The 1970 Brazil squad is often considered the greatest soccer team ever. With stars like Pelé, Jairzinho, and Rivelino, they showcased the beautiful game in its purest form. This article dives into their journey to World Cup glory and their lasting influence on soccer.',
    ),
    ('The Eternal Magic of Wembley Stadium',
    'assets/images/classic_soccer_16.jpg',
    'Wembley Stadium has witnessed countless historic moments, from England’s 1966 World Cup triumph to memorable club finals. This article celebrates the iconic venue and the legendary games and players that have graced its hallowed turf over the decades.',
    ),
  ];
}